# Generated by Django 5.2.8 on 2025-12-08 04:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(help_text='Start time in milliseconds')),
                ('end_time', models.BigIntegerField(help_text='End time in milliseconds')),
                ('computation_type', models.CharField(help_text='Type of computation (power_curve, classification, weibull, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True, help_text='Whether this is the latest computation for this time range')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbine_computations', to='facilities.farm')),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computations', to='facilities.turbines')),
            ],
            options={
                'ordering': ['-end_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(help_text='Classification status code (0-7)')),
                ('status_name', models.CharField(help_text='Human readable status name', max_length=50)),
                ('count', models.IntegerField(help_text='Number of data points with this status')),
                ('percentage', models.FloatField(help_text='Percentage of total data points')),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_summary', to='analytics.computation')),
            ],
            options={
                'ordering': ['status_code'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(help_text='Timestamp in milliseconds')),
                ('wind_speed', models.FloatField(help_text='Wind speed at this point')),
                ('active_power', models.FloatField(help_text='Active power at this point')),
                ('classification', models.IntegerField(help_text='Classification status code for this point')),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_points', to='analytics.computation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CapacityFactorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed_bin', models.FloatField(help_text='Wind speed bin value')),
                ('capacity_factor', models.FloatField(help_text='Capacity factor for this wind speed bin')),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_factors', to='analytics.computation')),
            ],
            options={
                'ordering': ['wind_speed_bin'],
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Production date (YYYY-MM-DD)')),
                ('daily_production', models.FloatField(help_text='Daily production value')),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_productions', to='analytics.computation')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_wind_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('reachable_energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('real_energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('loss_energy', models.FloatField()),
                ('loss_percent', models.FloatField()),
                ('rated_power', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tba', models.FloatField()),
                ('pba', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('partial_stop_loss', models.FloatField()),
                ('under_production_loss', models.FloatField()),
                ('curtailment_loss', models.FloatField()),
                ('partial_curtailment_loss', models.FloatField()),
                ('total_stop_points', models.IntegerField()),
                ('total_partial_stop_points', models.IntegerField()),
                ('total_under_production_points', models.IntegerField()),
                ('total_curtailment_points', models.IntegerField()),
                ('mtbf', models.FloatField(blank=True, help_text='Mean Time Between Failures', null=True)),
                ('mttr', models.FloatField(blank=True, help_text='Mean Time To Repair', null=True)),
                ('mttf', models.FloatField(blank=True, help_text='Mean Time To Failure', null=True)),
                ('time_step', models.FloatField()),
                ('total_duration', models.FloatField()),
                ('duration_without_error', models.FloatField()),
                ('up_periods_count', models.FloatField()),
                ('down_periods_count', models.FloatField()),
                ('up_periods_duration', models.FloatField()),
                ('down_periods_duration', models.FloatField()),
                ('aep_weibull_turbine', models.FloatField()),
                ('aep_weibull_wind_farm', models.FloatField(blank=True, help_text='Wind farm AEP (not calculated in current computation)', null=True)),
                ('aep_rayleigh_measured_4', models.FloatField()),
                ('aep_rayleigh_measured_5', models.FloatField()),
                ('aep_rayleigh_measured_6', models.FloatField()),
                ('aep_rayleigh_measured_7', models.FloatField()),
                ('aep_rayleigh_measured_8', models.FloatField()),
                ('aep_rayleigh_measured_9', models.FloatField()),
                ('aep_rayleigh_measured_10', models.FloatField()),
                ('aep_rayleigh_measured_11', models.FloatField()),
                ('aep_rayleigh_extrapolated_4', models.FloatField()),
                ('aep_rayleigh_extrapolated_5', models.FloatField()),
                ('aep_rayleigh_extrapolated_6', models.FloatField()),
                ('aep_rayleigh_extrapolated_7', models.FloatField()),
                ('aep_rayleigh_extrapolated_8', models.FloatField()),
                ('aep_rayleigh_extrapolated_9', models.FloatField()),
                ('aep_rayleigh_extrapolated_10', models.FloatField()),
                ('aep_rayleigh_extrapolated_11', models.FloatField()),
                ('yaw_misalignment', models.FloatField(blank=True, null=True)),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data', to='analytics.computation')),
            ],
        ),
        migrations.CreateModel(
            name='PowerCurveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_mode', models.CharField(choices=[('global', 'Chế độ toàn cục'), ('yearly', 'Chế độ theo năm'), ('quarterly', 'Chế độ theo quý'), ('monthly', 'Chế độ theo tháng'), ('day/night', 'Chế độ ngày/đêm')], default='global', max_length=20)),
                ('split_value', models.CharField(blank=True, help_text="Value for the split (e.g. 'day'/'night' for day_night mode, '1' for January in monthly mode)", max_length=20, null=True)),
                ('data_source', models.CharField(blank=True, max_length=50, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_curve_analyses', to='analytics.computation')),
            ],
        ),
        migrations.CreateModel(
            name='PowerCurveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.FloatField()),
                ('active_power', models.FloatField()),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_curve_points', to='analytics.powercurveanalysis')),
            ],
            options={
                'ordering': ['wind_speed'],
            },
        ),
        migrations.CreateModel(
            name='WeibullData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_parameter_a', models.FloatField(help_text='Weibull scale parameter (A)')),
                ('shape_parameter_k', models.FloatField(help_text='Weibull shape parameter (K)')),
                ('mean_wind_speed', models.FloatField(blank=True, help_text='Mean wind speed (Vmean) - calculated from data if available', null=True)),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weibull_data', to='analytics.computation')),
            ],
        ),
        migrations.CreateModel(
            name='YawErrorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField(help_text='Yaw error angle (X value)')),
                ('frequency', models.FloatField(help_text='Frequency/count at this angle (Y value)')),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaw_error_points', to='analytics.computation')),
            ],
            options={
                'ordering': ['angle'],
            },
        ),
        migrations.CreateModel(
            name='YawErrorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_error', models.FloatField(help_text='Mean yaw error')),
                ('median_error', models.FloatField(help_text='Median yaw error')),
                ('std_error', models.FloatField(help_text='Standard deviation of yaw error')),
                ('computation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yaw_error_statistics', to='analytics.computation')),
            ],
        ),
        migrations.AddIndex(
            model_name='computation',
            index=models.Index(fields=['turbine', 'computation_type', '-start_time'], name='analytics_c_turbine_3dafed_idx'),
        ),
        migrations.AddIndex(
            model_name='computation',
            index=models.Index(fields=['turbine', 'computation_type', '-end_time'], name='analytics_c_turbine_cba120_idx'),
        ),
        migrations.AddIndex(
            model_name='computation',
            index=models.Index(fields=['farm', 'computation_type', '-start_time'], name='analytics_c_farm_id_198e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='computation',
            index=models.Index(fields=['turbine', 'computation_type', 'is_latest'], name='analytics_c_turbine_f4f611_idx'),
        ),
        migrations.AddConstraint(
            model_name='computation',
            constraint=models.UniqueConstraint(fields=('turbine', 'computation_type', 'start_time', 'end_time', 'is_latest'), name='unique_latest_computation'),
        ),
        migrations.AddIndex(
            model_name='classificationsummary',
            index=models.Index(fields=['computation', 'status_code'], name='analytics_c_computa_92e28a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classificationsummary',
            unique_together={('computation', 'status_code')},
        ),
        migrations.AddIndex(
            model_name='classificationpoint',
            index=models.Index(fields=['computation', 'timestamp'], name='analytics_c_computa_e2218b_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationpoint',
            index=models.Index(fields=['computation', 'classification'], name='analytics_c_computa_b5dc94_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityfactordata',
            index=models.Index(fields=['computation', 'wind_speed_bin'], name='analytics_c_computa_f4e009_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='capacityfactordata',
            unique_together={('computation', 'wind_speed_bin')},
        ),
        migrations.AddIndex(
            model_name='dailyproduction',
            index=models.Index(fields=['computation', 'date'], name='analytics_d_computa_8dbb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyproduction',
            index=models.Index(fields=['computation', '-date'], name='analytics_d_computa_cc6685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyproduction',
            unique_together={('computation', 'date')},
        ),
        migrations.AddIndex(
            model_name='indicatordata',
            index=models.Index(fields=['computation'], name='analytics_i_computa_b47ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='weibulldata',
            index=models.Index(fields=['computation'], name='analytics_w_computa_2e3e07_idx'),
        ),
        migrations.AddIndex(
            model_name='yawerrordata',
            index=models.Index(fields=['computation'], name='analytics_y_computa_931994_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yawerrordata',
            unique_together={('computation', 'angle')},
        ),
        migrations.AddIndex(
            model_name='yawerrorstatistics',
            index=models.Index(fields=['computation'], name='analytics_y_computa_48d988_idx'),
        ),
    ]
