# Generated by Django 5.2.8 on 2026-01-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computation',
            name='p_rated',
            field=models.FloatField(blank=True, help_text='Rated power (kW) - estimated from SCADA', null=True),
        ),
        migrations.AddField(
            model_name='computation',
            name='v_cutin',
            field=models.FloatField(blank=True, help_text='Cut-in wind speed (m/s) - estimated from SCADA', null=True),
        ),
        migrations.AddField(
            model_name='computation',
            name='v_cutout',
            field=models.FloatField(blank=True, help_text='Cut-out wind speed (m/s) - estimated from SCADA', null=True),
        ),
        migrations.AddField(
            model_name='computation',
            name='v_rated',
            field=models.FloatField(blank=True, help_text='Rated wind speed (m/s) - estimated from SCADA', null=True),
        ),
    ]
