# Generated by Django 5.2.8 on 2026-01-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_computation_p_rated_computation_v_cutin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordata',
            name='failure_count',
            field=models.IntegerField(default=0, help_text='Number of failures (UP→STOP transitions, merged) for this computation range'),
        ),
        migrations.CreateModel(
            name='FailureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_ms', models.BigIntegerField(help_text='Failure start timestamp (ms)')),
                ('end_time_ms', models.BigIntegerField(help_text='Failure end timestamp (ms)')),
                ('duration_s', models.FloatField(help_text='Failure duration (seconds)')),
                ('status', models.CharField(default='STOP', help_text='Down status label for this event (default STOP)', max_length=32)),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_events', to='analytics.computation')),
            ],
            options={
                'ordering': ['start_time_ms'],
                'indexes': [models.Index(fields=['computation', 'start_time_ms'], name='analytics_f_computa_11eb21_idx'), models.Index(fields=['computation', 'end_time_ms'], name='analytics_f_computa_d71b02_idx')],
            },
        ),
    ]
