# Generated by Django 5.2.8 on 2026-01-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_indicatordata_failure_count_failureevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failureevent',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveIndex(
            model_name='failureevent',
            name='analytics_f_computa_11eb21_idx',
        ),
        migrations.RemoveIndex(
            model_name='failureevent',
            name='analytics_f_computa_d71b02_idx',
        ),
        migrations.RenameField(
            model_name='failureevent',
            old_name='end_time_ms',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='failureevent',
            old_name='start_time_ms',
            new_name='start_time',
        ),
        migrations.AddIndex(
            model_name='failureevent',
            index=models.Index(fields=['computation', 'start_time'], name='analytics_f_computa_217333_idx'),
        ),
        migrations.AddIndex(
            model_name='failureevent',
            index=models.Index(fields=['computation', 'end_time'], name='analytics_f_computa_01a273_idx'),
        ),
    ]
