# Generated by Cursor on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_failureevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computation",
            name="algorithm_version",
            field=models.CharField(
                blank=True,
                help_text="Algorithm version identifier for traceability (e.g. v1, 2026-02-26)",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="computation",
            name="code_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash of computation code/config used to generate this result",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="indicatordata",
            name="capacity_factor",
            field=models.FloatField(
                blank=True,
                help_text="Capacity factor (overall) = RealEnergy / (RatedPower * TotalHours)",
                null=True,
            ),
        ),
    ]

