# Generated by Django 5.2.8 on 2026-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_dailyproduction_daily_reachable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='daily_production',
            field=models.FloatField(help_text='Daily real production value (kWh)'),
        ),
    ]
