# Generated by Django 5.2.8 on 2025-12-03 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Main Admin'), ('investor', 'Investor'), ('farm_admin', 'Farm Admin'), ('staff', 'Operator')], default='staff', max_length=20)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.farm')),
                ('groups', models.ManyToManyField(blank=True, related_name='account_groups', to='auth.group')),
                ('investor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='facilities.investor')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to='permissions.account')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='account_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('is_permanent', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_account', to='facilities.investor')),
            ],
        ),
    ]
