# Generated by Django 5.2.8 on 2025-12-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('farm', 'Farm Level'), ('turbine', 'Turbine Level')], max_length=20)),
                ('column_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SmartHIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('token', models.TextField(blank=True, default='', null=True)),
                ('point_check_expired', models.CharField(default='GT1.Grid.totW', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facilities.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('active_power', models.FloatField(null=True, verbose_name='Power generate of farm (MW)')),
                ('wind_speed', models.FloatField(null=True, verbose_name='Wind speed at 100m (m/s)')),
                ('wind_dir', models.FloatField(null=True, verbose_name='Wind direction at 100m')),
                ('air_temp', models.FloatField(null=True, verbose_name='Ambient Temperature (oC)')),
                ('pressure', models.FloatField(null=True, verbose_name='Air pressure of farm (%)')),
                ('hud', models.FloatField(null=True, verbose_name='Relative humidity of farm (%)')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acquisition_historical', to='facilities.farm')),
            ],
            options={
                'verbose_name': 'Factory Historical Data',
                'verbose_name_plural': 'Factory Historical Data',
                'ordering': ('time_stamp',),
                'unique_together': {('farm', 'time_stamp')},
            },
        ),
        migrations.CreateModel(
            name='HISPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_HIS', to='facilities.farm')),
                ('turbine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_HIS', to='facilities.turbines')),
                ('point_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition.pointtype')),
            ],
            options={
                'unique_together': {('farm', 'point_type', 'turbine')},
            },
        ),
    ]
