# Generated by Django 5.2.8 on 2025-12-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factoryhistorical',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='factoryhistorical',
            name='turbine',
            field=models.ForeignKey(blank=True, help_text='Null for farm-level data, set for turbine-level data', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turbine_historical', to='facilities.turbines'),
        ),
        migrations.AlterField(
            model_name='factoryhistorical',
            name='active_power',
            field=models.FloatField(null=True, verbose_name='Active Power (MW)'),
        ),
        migrations.AlterField(
            model_name='factoryhistorical',
            name='hud',
            field=models.FloatField(null=True, verbose_name='Relative humidity (%)'),
        ),
        migrations.AlterField(
            model_name='factoryhistorical',
            name='pressure',
            field=models.FloatField(null=True, verbose_name='Air pressure (%)'),
        ),
        migrations.AddIndex(
            model_name='factoryhistorical',
            index=models.Index(fields=['farm', 'turbine', 'time_stamp'], name='acquisition_farm_id_3b5b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='factoryhistorical',
            index=models.Index(fields=['farm', 'time_stamp'], name='acquisition_farm_id_14c6a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='factoryhistorical',
            constraint=models.UniqueConstraint(condition=models.Q(('turbine__isnull', True)), fields=('farm', 'time_stamp'), name='unique_farm_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='factoryhistorical',
            constraint=models.UniqueConstraint(condition=models.Q(('turbine__isnull', False)), fields=('farm', 'turbine', 'time_stamp'), name='unique_turbine_timestamp'),
        ),
    ]
