# Generated by Django 5.2.8 on 2025-12-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0002_alter_factoryhistorical_unique_together_and_more'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='factoryhistorical',
            name='unique_farm_timestamp',
        ),
        migrations.RemoveConstraint(
            model_name='factoryhistorical',
            name='unique_turbine_timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='factoryhistorical',
            unique_together={('farm', 'turbine', 'time_stamp')},
        ),
    ]
