# Generated by Django 5.2.8 on 2026-02-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0004_scadaunitconfig'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scadaunitconfig',
            new_name='acquisition_farm_id_790d3c_idx',
            old_name='acquisition_farm_turbine_source_idx',
        ),
        migrations.RenameIndex(
            model_name='scadaunitconfig',
            new_name='acquisition_turbine_8ad244_idx',
            old_name='acquisition_turbine_source_idx',
        ),
        migrations.RenameIndex(
            model_name='scadaunitconfig',
            new_name='acquisition_farm_id_ca020c_idx',
            old_name='acquisition_farm_source_idx',
        ),
    ]
