"""
Django settings for smartwpa project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hvam)@(fnw!*9a3w3*%owq8%t@(e45-s_qh18tw_b$qz!6&nzg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.10.10.106']

CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "OPTIONS",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    
    # Local apps
    'permissions',
    'facilities',
    'acquisition',
    'api_gateway',
    'analytics',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes= 60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days= 7),
    'ROTATE_REFRESH_TOKENS': True,

    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(minutes=15),  # Thời gian cập nhật tự động
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',  # Claim để kiểm soát thời gian cập nhật
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
    'BLACKLIST_ENABLED': True,

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'smartwpa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartwpa.wsgi.application'
AUTH_USER_MODEL = "permissions.Account"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, 'mysql.cnf'),
        },
        'CONN_MAX_AGE': 15 * 60 #s
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
# Đảm bảo folder logs tồn tại
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {name} {pathname}:{lineno} {funcName} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        # Django framework logs
        'file_django': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # API Gateway logs (management + turbines_analysis)
        'file_api_gateway': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'api_gateway.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Acquisition logs (modbus, smarthis, influx_db, scheduler)
        'file_acquisition': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'acquisition.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Permissions logs
        'file_permissions': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'permissions.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Facilities logs
        'file_facilities': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'facilities.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # All ERROR level logs (centralized error tracking)
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        # Console handler
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Django framework
        'django': {
            'handlers': ['file_django', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_django', 'file_errors', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file_django', 'console'],
            'level': 'ERROR',  # Chỉ log ERROR từ development server, bỏ qua 4xx warnings
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file_django', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        
        # API Gateway - Management (auth, license, users, farms, turbines, acquisition, common)
        'api_gateway.management': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api_gateway.management.auth': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,  # Propagate to parent
        },
        'api_gateway.management.license': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'api_gateway.management.users': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'api_gateway.management.farms': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'api_gateway.management.turbines': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'api_gateway.management.acquisition': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'api_gateway.management.common': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        
        # API Gateway - Turbines Analysis
        'api_gateway.turbines_analysis': {
            'handlers': ['file_api_gateway', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        
        # Acquisition - All submodules (modbus, smarthis, influx_db, scheduler)
        'acquisition': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'acquisition.modbus_master': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.modbus_master.connection': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.modbus_master.data_reader': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.modbus_master.data_storage': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.smarthis': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.smarthis.get_data': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.smarthis.restful_client': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.smarthis.handle_time': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.smarthis.save_data': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.influx_db': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.influx_db.sync_service': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.influx_db.influx_service': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.influx_db.influxdb_client': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.influx_db.config_manager': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'acquisition.scheduler': {
            'handlers': ['file_acquisition', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        
        # Permissions
        'permissions': {
            'handlers': ['file_permissions', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        
        # Facilities
        'facilities': {
            'handlers': ['file_facilities', 'file_errors', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['file_errors', 'console'],
        'level': 'WARNING',
    },
}

# Scheduler Configuration
SCHEDULER_CONFIG = {
    'MAIN_SYNC_INTERVAL_MINUTES': 15,
    'MODBUS_COLLECTION_INTERVAL_MINUTES': 5,
    'CONNECTION_CHECK_INTERVAL_HOURS': 1,
    'TIMEZONE': 'Asia/Ho_Chi_Minh',
}